defaults:
  - &headers
    headers:
      - "Access-Control-Allow-Origin: https://geradordeletras.com.br"

# Define the headers for the whole site
# The defaults key is required and must have a value of an array of hashes
# Each hash must contain a headers key, which must have an array of headers as its value
# This will set the headers for all pages in the site
defaults:
  - scope:
      path: "/"
    values:
      <<: *headers

# Define headers for specific directories
# This will set the headers for all pages in the `assets` directory
defaults:
  - scope:
      path: "/assets/"
    values:
      <<: *headers
